### ISSUE TITLE
roller can't start rollapp 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#1133]
```
ubuntu@ip-172-31-18-177:~$ roller rollapp start
panic: runtime error: slice bounds out of range [:6] with length 0

goroutine 1 [running]:
github.com/dymensionxyz/roller/cmd/rollapp/start.Cmd.func1(0xc000933b08, {0x1e5b3fe?, 0x4?, 0x1e5b402?})
	/go/src/github.com/dymensionxyz/roller/cmd/rollapp/start/start.go:79 +0xc65
github.com/spf13/cobra.(*Command).execute(0xc000933b08, {0x38806c0, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x38369e0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/dymensionxyz/roller/cmd.Execute()
	/go/src/github.com/dymensionxyz/roller/cmd/root.go:28 +0x1a
main.main()
	/go/src/github.com/dymensionxyz/roller/main.go:6 +0xf
```

**Comment by omritoptix** [comment]
was due to insufficeient storage
