### ISSUE TITLE
When i try to connect via metamask i got error on JS console

### ISSUE THREAD

**Issue by s4253** [dymensionxyz/roller#763]
### Roller version

roller version

### OS

lubuntu 23 with google chrome

### Processor Architecture

Linux speedo 6.5.0-21-generic 

### Steps to reproduce it

Install lubunut 23
install google chrome 122
go to portal.dymension.xyz
Try connect to dymension network via metamask, stuck with js error in the console. Metamask is not opening. Everything is working with firefox.

### Expected result

Metamask ask me to add dymension network

### Actual result

Nothing

### Relevant log output

```Shell
error KEY_NOT_FOUND dymension_1100-1 Error: Internal JSON-RPC error.
    at Proxy.s (<anonymous>:1:65793)
    at async K.getAccounts (ethereum-wallet.ts:164:15)
    at async K.getAddress (ethereum-wallet.ts:91:15)
overrideMethod @ console.js:213
p @ portal-error.ts:13
q @ wallet-error.ts:24
(anonymous) @ ethereum-wallet.ts:165
Promise.catch (async)
getAccounts @ ethereum-wallet.ts:164
await in getAccounts (async)
getAddress @ ethereum-wallet.ts:91
(anonymous) @ use-account-network.ts:52
rc @ react-dom.production.min.js:244
Ed @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
E @ scheduler.production.min.js:13
F @ scheduler.production.min.js:14
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
_ @ scheduler.production.min.js:14
F @ scheduler.production.min.js:14
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
_ @ scheduler.production.min.js:14
F @ scheduler.production.min.js:14
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
_ @ scheduler.production.min.js:14
P @ scheduler.production.min.js:14
t.unstable_scheduleCallback @ scheduler.production.min.js:18
Sd @ react-dom.production.min.js:297
(anonymous) @ react-dom.production.min.js:282
Cd @ react-dom.production.min.js:281
cd @ react-dom.production.min.js:273
Lo @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 34 more frames
Show less
metrics:1 Third-party cookie will be blocked. Learn more in the Issues tab.
```

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

`KEY_NOT_FOUND` error generally occurs when the key isn't funded
